name: Rnalter
description: Blogging about security
meta_description: "Rnalter, Blogging about security"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://rnalter.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Shivankar"

# Disqus config
disqus-shortname: ""
